name: Run Tests

on:
  push:
    branches: [main, organize_and_test]
    paths:
      - "audify/**"
      - "tests/**"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "audify/**"
      - "tests/**"
      - ".github/workflows/tests.yml"
    branches: [main, organize_and_test]
jobs:
  unittest:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # get python version from ./nhsflame-api/.python-version file
          # if not found, use 3.11
          python-version: ${{ github.event.inputs.python-version || '3.11' }}

      - name: Install uv (if used for dependency management)
        run: pip install uv

      - name: Run tests with pytest and coverage
        run: uv run task test

      - name: Generate coverage report
        run: uv run coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
